services:
  frontend:
    container_name: frontend
    build:
      context: ./cep-e-noticias
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context:  ../G4F-MRE-API
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    working_dir: /backend
    command: npm start
  db:
    build:
      context:  ../G4F-MRE-API
      dockerfile: Dockerfile
    image: db
    container_name: db
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
    working_dir: /backend
    command: npm run server